### ISSUE TITLE
lint: upgrade to ESLint

### ISSUE THREAD

**Issue by shellscape** [gilt/gilt-swig-assets#28]
JSHint has fallen behind the times and lacks remotely proper support for ES6. ESLint supports ES6 syntax and has a superior tooling experience with setup and output. Configuration options for ESLint are much more robust, allowing for validation of whitespace and format as well as code syntax.

**Comment by Meesayen** [comment]
What about http://standardjs.com ? It is basically an ESLint based, pre-configured JS style checker.
The only caveat is that it tries to promote the drop of the semicolon. If we want to use semicolons we can use its variant: `semistandard` 😄

**Comment by shellscape** [comment]
I personally prefer something configurable that allows evolution of a style guide versus an authoritarian component that can change at any time based on the authors' opinions, at which point you're stuck having to comply, whether you like it or not. standardjs' argument that too much bikeshedding occurs over style, resulting in the need for standardjs, is malarky at Gilt. And then there's [this fun bit from their site](http://standardjs.com/#how-do-i-hide-a-certain-warning):

>JavaScript Standard Style uses eslint under-the-hood and you can hide warnings as you normally would if you used eslint directly.

And then there's the semicolon. I prefer sanity, so you won't catch me dropping semicolons anytime soon. However, dublin is of course welcome to take its own course, as it's now solely responsible for customer facing front end.

**Comment by Meesayen** [comment]
Closed by https://github.com/gilt/gilt-swig-assets/pull/38
