### ISSUE TITLE
specs: Use Default Reporters

### ISSUE THREAD

**Issue by shellscape** [gilt/gilt-swig-assets#45]
Finally got CI working on ui-tracking, and nyan doesn't play well with it. It's gonna make debugging any failed builds pretty tough because of the additional length that nyan adds to the output in Travis.

We'll have to change up these two spots:
https://github.com/gilt/gilt-swig-assets/blob/66a3c0223adb31fe92ee8ac94ab350f7d516cb75/lib/swig-spec/templates/jasmine-runner.mustache#L48

https://github.com/gilt/gilt-swig-assets/blob/66a3c0223adb31fe92ee8ac94ab350f7d516cb75/lib/swig-spec/lib/frameworks/mocha.js#L57

And use some kind of `--noreporter` or `--nonyan` or `--travis` or `--ci` or something to signal the code that we need the default reporters to be used.

**Comment by ahollinshead** [comment]
Could we just drop nyan and replace it with something that doesn't have as much output?

**Comment by shellscape** [comment]
I hope not. I love nyan running locally.

**Comment by RoryH** [comment]
This subject only came to mind today for me. I would prefer to use the default report in all environments. As fond as I am of Nyan cat, it just does not report the information we need... for example here's the output with 1 failing test using the --verbose flag...

![Nyan cat lack of info](http://i.imgur.com/Zv8tLd0.jpg)

It's just not giving the information we need and the novelty most definitely runs out after a while.

**Comment by ahollinshead** [comment]
If another reporter can give us clearer output as to what failed, that would far outweigh any fun. I think Nyan looks a bit naff but if it's behaviour-neutral I don't mind it saying

**Comment by shellscape** [comment]
and we're off topic. the reporter doesn't give you the right output because of other issues. for mocha specs it will, for jasmine specs, it won't. I outlined why in #43.

**Comment by RoryH** [comment]
@shellscape The reporter output above is from mocha specs. I wouldn't consider that adequate output if it's not giving information about the tests that failed. And regardless the test framework that is being use should be irrelevant to whether output works or not.

To stay on topic I propose closing this issue and opening a new one to remove Nyan reporter from the specs

**Comment by ahollinshead** [comment]
The title is "specs: Use Default Reporters" - how is changing from nyan cat to the default reporter off topic @shellscape ?

**Comment by shellscape** [comment]
dunno why I even bother. you guys end up doing whatever the heck you want anyhow.

**Comment by ahollinshead** [comment]
you bother because you care @shellscape I assume. Please give some reasons apart from 'fun' for not changing. Rory has given a functional reason why default reporters would be better. That's where I see the debate right now.
